### PR TITLE
Cross build

### PR DESCRIPTION
**Pull request by onzo-mateuszzakarczemny**
| Q               | A
| --------------- | ---
| Bug fix?        | no
| New feature?    | yes
| API breaks?     | no
| Deprecations?   | no
| Related tickets | ?
| License         | Apache 2.0

### What's in this PR?
- Upgrade spark version to 2.4.4
- Add cross build against scala 2.11 and 2.12

### Why?
New spark support scala 2.12. It would be nice to have cross compiled version of this library.

### Additional context
Some spark objects (eg. Sink) were moved to private package. Therefore I had to create proxy objects to them.

### CODE REVIEW

**Comment by stoader** [comment]
@onzo-mateuszzakarczemny looks like using `NonPrivateSecurityManager` in the PrometheusSink constructor doesn't work when Spark tries to instantiate PrometheusSink class. This https://github.com/apache/spark/blob/v2.4.4/core/src/main/scala/org/apache/spark/metrics/MetricsSystem.scala#L199 is the code in Spark responsible to instantiate registered Sinks and looks for a constructor that has `SecurityManager` as its third parameter and this type doesn't match `NonPrivateSecurityManager`. 

This causes  
```
java.lang.NoSuchMethodException: com.banzaicloud.spark.metrics.sink.PrometheusSink.<init>(java.util.Properties, com.codahale.metrics.MetricRegistry, org.apache.spark.SecurityManager)       
  at java.lang.Class.getConstructor0(Class.java:3082)                                                                                                                                      
  at java.lang.Class.getConstructor(Class.java:1825)                                                                                                                                       
  at org.apache.spark.metrics.MetricsSystem$$anonfun$registerSinks$1.apply(MetricsSystem.scala:199) 
```

**Comment by onzo-mateuszzakarczemny** [comment]
I'll try to fix that

**Comment by onzo-mateuszzakarczemny** [comment]
@stoader How did you build this previously?
In Spark 2.3 those SecurityManager is also private.
https://github.com/apache/spark/blob/v2.3.0/core/src/main/scala/org/apache/spark/metrics/MetricsSystem.scala#L70

But SecurityManager in decompiled `lib/spark-core_2.11-2.3.jar` is public. It was a customized jar?

**Comment by stoader** [comment]
Yes that was a customized jar in which we made all necessary types public

**Comment by onzo-mateuszzakarczemny** [comment]
@stoader I created another PR to fix that (+test) - https://github.com/banzaicloud/spark-metrics/pull/45/files

**Pull request merged**
