### PR TITLE
Fix prometheus sink loading

### PR DESCRIPTION
**Pull request by onzo-mateuszzakarczemny**
| Q               | A
| --------------- | ---
| Bug fix?        | no|yes
| New feature?    | no|yes
| API breaks?     | no|yes
| Deprecations?   | no|yes
| Related tickets | fixes #X, partially #Y, mentioned in #Z
| License         | Apache 2.0

### Checklist

- [ ] Error handling code meets the [guideline](https://github.com/banzaicloud/pipeline/blob/master/docs/error-handling-guide.md)
- [ ] Logging code meets the guideline (TODO)
- [ ] User guide and development docs updated (if needed)
- [ ] Related Helm chart(s) updated (if needed)

### To Do

- [ ] If the PR is not complete but you want to discuss the approach, list what remains to be done here

### CODE REVIEW

**Comment by onzo-mateuszzakarczemny** [comment]
@stoader I don't believe that maven validate that. I think you could still publish under `com.banzaicloud` group with different packages in the jar file.

**Comment by onzo-mateuszzakarczemny** [comment]
I thin groupon use similar technique - https://github.com/groupon/spark-metrics/blob/master/src/main/scala/org/apache/spark/groupon/metrics/Sink.scala

**Comment by stoader** [comment]
That makes sense. Can you change the package name to `org.apache.spark.banzaicloud.metrics` (similar pattern groupon uses) and also update https://github.com/banzaicloud/spark-metrics/blob/master/PrometheusSink.md to reflect the modified package name?

**Comment by onzo-mateuszzakarczemny** [comment]
@stoader Done

**Comment by stoader** [comment]
I don't understand why but still can't instantiate the Sink even though it extends the Logging trait. 
```Caused by: java.lang.NoSuchMethodError: org.apache.spark.internal.Logging.$init$(Lorg/apache/spark/internal/Logging;)V
at com.banzaicloud.spark.metrics.sink.PrometheusSink.<init>(PrometheusSink.scala:41)
at org.apache.spark.banzaicloud.metrics.sink.PrometheusSink.<init>(PrometheusSink.scala:12)```

Any idea?

**Comment by stoader** [comment]
My bad the issue was that I used spark-metrics compiled with Scala 2.12 with Spark 2.4.4 compiled with Scala 2.11

**Pull request merged**
